// constants.js
export const weaponOptions = [
  { category: 'Pistol', title: 'Wildfire' },
  { category: 'Pistol', title: 'Jaws' },
  { category: 'Pistol', title: 'Hunter' },
  { category: 'Pistol', title: 'Momento' },
  { category: 'Pistol', title: 'Hammerhead Shark' },
  { category: 'Pistol', title: 'Hazardous Object' },
  { category: 'Pistol', title: 'Dusty' },
  { category: 'Shotgun', title: 'Dual Fury' },
  { category: 'Shotgun', title: 'Old Huntsman' },
  { category: 'Shotgun', title: 'Sandstorm' },
  { category: 'Shotgun', title: 'Doombringer' },
  { category: 'Shotgun', title: 'Raining Cash' },
  { category: 'Shotgun', title: 'Backfire' },
  { category: 'Shotgun', title: 'Corrosion' },
  { category: 'Shotgun', title: 'Netherworld' },
  { category: 'Shotgun', title: 'Pyroclasm' },
  { category: 'SMG', title: 'Outer Space' },
  { category: 'SMG', title: 'Blue Tiger' },
  { category: 'SMG', title: 'Div-Evo' },
  { category: 'SMG', title: 'Kumawink' },
  { category: 'SMG', title: 'Little Jaws' },
  { category: 'SMG', title: 'Primal Rage' },
  { category: 'SMG', title: 'Icy Rain' },
  { category: 'Rifle', title: 'Pioneer' },
  { category: 'Rifle', title: 'Outsider' },
  { category: 'Rifle', title: 'Abyss Glance' },
  { category: 'Rifle', title: 'Crank' },
  { category: 'Rifle', title: 'The Last Valor' },
  { category: 'Rifle', title: 'Silent Anabasis' },
  { category: 'Sniper', title: 'Brahminy' },
  { category: 'Sniper', title: 'Gulped Lore' },
  { category: 'Sniper', title: 'Crumble' },
  { category: 'Sniper', title: 'Black Panther' },
  { category: 'Sniper', title: 'Bullseye' },
  { category: 'LMG', title: 'Predator' },
  { category: 'LMG', title: 'Wrath Of Hades' },
  { category: 'LMG', title: 'Mr Squid' },
  { category: 'LMG', title: 'Boom! Boom!' },
  { category: 'LMG', title: 'Conflicting Memories' },
  { category: 'LMG', title: 'Icebreaker' },
  { category: 'Bow', title: 'Compound Bow' },
  { category: 'Bow', title: 'Compound Bow' },
  { category: 'Bow', title: 'Critical Pulse' },
  { category: 'Bow', title: 'Recurve Bow' },
];
export const wepmodOptions = [
  { category: 'Burn', title: 'Burning Wrath' },
  { category: 'Burn', title: 'Flame Resonance' },
  { category: 'Burn', title: 'Blaze Blessing' },
  { category: 'Burn', title: 'Embers' },
  { category: 'Frost Vortex', title: 'Frosty Blessing' },
  { category: 'Frost Vortex', title: 'Vortex Multiplier' },
  { category: 'Frost Vortex', title: 'Shattering Ice' },
  { category: 'Frost Vortex', title: 'Cryo Blast' },
  { category: 'Power Surge', title: 'Surge Amplifier' },
  { category: 'Power Surge', title: 'Static Shock' },
  { category: 'Power Surge', title: 'Shock Diffusion' },
  { category: 'Power Surge', title: 'Shock Rampage' },
  { category: 'Unstable Bomber', title: 'Heavy Explosives' },
  { category: 'Unstable Bomber', title: 'Bombardier Souvenir' },
  { category: 'Unstable Bomber', title: 'Reckless Bomber' },
  { category: 'Unstable Bomber', title: 'Super Charged' },
  { category: 'Shrapnel', title: 'Shield Breaker' },
  { category: 'Shrapnel', title: 'Shrapnel Souvenir' },
  { category: 'Shrapnel', title: 'Shatter Them All' },
  { category: 'Shrapnel', title: 'Shrapnel Smash' },
  { category: 'Fast Gunner', title: 'Cowboy' },
  { category: 'Fast Gunner', title: 'Shoot Out' },
  { category: 'Fast Gunner', title: 'Shooting Blitz' },
  { category: 'Fast Gunner', title: 'Precision Rush' },
  { category: 'Bull Eye', title: 'Recover Mark' },
  { category: 'Bull Eye', title: 'Hunters Perk' },
  { category: 'Bull Eye', title: 'Vulnerability Amplifier' },
  { category: 'Bull Eye', title: 'Spreading Marks' },
  { category: 'Fortress Warfare', title: 'United We Stand' },
  { category: 'Fortress Warfare', title: 'Final Territory' },
  { category: 'Fortress Warfare', title: 'Durable Territory' },
  { category: 'Fortress Warfare', title: 'Portable Territory' },
  { category: 'Bounce', title: 'Targeted Bounce' },
  { category: 'Bounce', title: 'Bounce Rampage' },
  { category: 'Bounce', title: 'Not Throw Away Your Shot' },
  { category: 'Bounce', title: 'Super Bullet' },
];
export const effectOptions = [
  /* Third Options Array */
  '< Talents > Elements',
  '< Violents > Crit DMG',
  '< Precision > Weakspot DMG',
  '<Resonance> ED > CD',
  '<Resonance> ED > WD',
  '<Resonance> WD > CD',
  '<Resonance> CD > ED',
  '<Resonance> WD > ED',
  '<Lunar Oracle>',
  '<Burn> Burn DMG',
  '<PS> Power Surge DMG',
  '<FV> Frost Vortex DMG',
  "<BE> CD Target With Bull's Eye",
  "<BE> WD Target with Bull's Eye",
  '<FW> While in FW Weapon DMG',
  '<UB> Unstable Bomber DMG',
  '<FG> When in FG Weapon DMG',
  '<Bounce> Bounce DMG',
  '<Sharpnel> Sharpnel DMG',
  'Weapon DMG',
  'Status DMG',
  'Magazine Capacity',
  'Reload Speed Bonus',
  'DMG against Great Ones',
  'DMG against Elite',
  'DMG against Normal',
  'Max HP',
  'Head DMG Reduction',
  'Weapon DMG Reduction',
  'Status DMG Reduction',
  '<Resonance> ED > CD',
  '<Resonance> ED > WD',
  '<Resonance> WD > CD',
  '<Resonance> CD > ED',
  '<Resonance> WD > ED',
  'Blaze DMG',
  'Burn Trigger Time',
  'Burn Trigger Chance',
  'DMG on Target with PS',
  'Shock DMG',
  'Power Surge Crit DMG',
  'PS Trigger Chance',
  'Frost DMG',
  'FV Trigger Chance',
  'Frost Vortex Duration',
  "Bull's Eye Duration",
  "Bull's Eye Trigger Chance",
  'While in FW Weakspot DMG',
  'While in FW Crit DMG',
  'FW Trigger Chance',
  'Blast DMG',
  'UB Trigger Chance',
  'UB Crit DMG',
  'When in FG Crit DMG',
  'When in FG Weakspot DMG',
  'Bounce Crit DMG',
  'Bounce Trigger Chance',
  'Bounce Weakspot DMG',
  'Sharpnel Crit DMG',
  'Sharpnel Trigger Chance',
  'Sharpnel Weakspot DMG',
];
export const styleOptions = [
  'Assault',
  'Boost',
  'Energy',
  'Frugal',
  'Heavy',
  'Light',
  'Overflow',
  'Portable',
  'Precision',
  'Rapid Shot',
  'Stabilized',
  'Vanguard', /* ... */];
export const stat1Options = [
  'Crit Rate',
  'Crit DMG',
  'Elemental DMG',
  'Weakspot DMG',
];
export const stat2Options = stat1Options; // Reuse stat1Options
export const cradleOptions = [
  'Anti-Regen',
  'Anti-Void',
  'Anti-Phase',
  'Deviant Energy Defense',
  'Sky Operation',
  'Override',
  'Tactical Combo',
  'Status Enhancement',
  'Deviation Master',
  'Lone Walker',
  'Side by Side',
  'Deadly Combat',
  'Sustained Suppression',
  'First Round Blast',
  'Steady Hand',
  'Ammo Cascade',
  'Frost Sense',
  'Heat Agglutination',
  'Tracking Bullet',
  'Bounce Rampage',
  'Series Detonation',
  'Fortress Link',
  'Overload',
  'Bounty Hunter',
  'Fast Pursuit',

  'Anti-Coherence',
  'Rapid Aid',
  'Energy Surge',
  'Chaotic Thoughts',
  'Deadly Combo',
  'Elemental Sense',
  'Marked Strike',
  'Robust',
  'Extreme Freezing',
  'Blazing Detonation',
  'Invincible Strike',
  'Bounce Rampage',
  'Explosives Bonus',
  'Heavy Strike',
  'Transient Impact',
  'Brawl Boost',
];
export const DevOptions = [
  "Lonewolf's Whisper",
  "Butterfly's Emissary",
  'By the Wind',
  'Polar Jelly',
  'Dr. Teddy',
  'Enchanting Void',
  'Festering Gel',
  'Grumpy Bulb',
  'Mini Feaster',
  'Mini Wonder',
  'Mr. Wish',
  'Pyro Dino',
  'Shattered Maiden',
  'Voodoo Doll',
  'Zeno-Purifier',
  'Zapcam',
  'Invincible Sun',
  'Snowsprite',
];
export const FoodOptions = [
  'Canned Sea Food in Oil [Baracuda]',
  'Canned Sea Food in Oil [Sea Bass]',
  'Canned Sea Food in Oil [Angelfish]',
  'Canned Sea Food in Oil [Pompano]',
  'Stargazy Pie',
  'Honey Glazed Meat',
  'Crumbly Bread',
  'Popcorn',
  'Flaming Eggtart',
  'Ginger Poppers',
  'Gingerdrop',
  'Sprakling Pumkin Soup',
  'Canned Minty Meat',
  'Hearty Meat Stew',
  'Canned Spicy Rabbit Dices',
  'Assorted Canned Fruit',
  'French Fries',
  'Mixed Fried Hot Dog',
  'Canned Steak',
  'Stardust Pumkin Salad',
  'Bone-in Deviated Sausage',
];
export const DrinkOptions = [
  'Stardust Raspberry Shaved Ice',
  'Whimsical Drink',
  'Iced Tea',
  'Corn Ale',
];
const setItems = [
  { category: 'Set', title: 'Lonewolf' },
  { category: 'Set', title: 'Renegade' },
  { category: 'Set', title: 'Shelterer' },
  { category: 'Set', title: 'Savior' },
  { category: 'Set', title: 'Stromweaver' },
  { category: 'Set', title: 'Bastille' },
  { category: 'Set', title: 'Black Stone' },
  { category: 'Set', title: 'Treacherous Tides' },
  { category: 'Set', title: 'Agent' },
  { category: 'Set', title: 'Heavy Duty' },
  { category: 'Set', title: 'Falcon' },
  { category: 'Set', title: 'Blast' },
  { category: 'Set', title: 'Scout' },
];
export const helmetOptions = [
  { category: 'Key', title: 'Mayfly Goggles' },
  { category: 'Key', title: 'Cage Helmet' },
  { category: 'Key', title: 'Gas-Tight Helmet' },
  { category: 'Key', title: 'Yellow Paint Mask' },
  { category: 'Key', title: 'Gas Mask Hood' },
  { category: 'Key', title: 'Beret' },
  ...setItems,
];
export const hmodOptions = [
  'Lifeforce Boost',
  'Fateful Strike',
  'Deviation Expert',
  'Elemental Havoc',
  'Momentum Up',
  'Precise Strike',
  'Work of Proficiency',
  'Mag Extension',
  'First-Move Advantage',
  'Weapon Symphony',
  'Quick Toss',
];
export const faceOptions = [
  { category: 'Key', title: 'Dust Mask' },
  { category: 'Key', title: 'Oasis Mask' },
  { category: 'Key', title: 'Precise Shot Mask' },
  { category: 'Key', title: 'Viper Mask' },
  ...setItems,
];
export const fmodOptions = [
  { category: 'Burn', title: 'Retrusion Explosion' },
  { category: 'Burn', title: 'Blaze Amplifier' },
  { category: 'Frost Vortex', title: 'Frost Construct' },
  { category: 'Frost Vortex', title: 'Obliteration' },
  { category: 'Power Surge', title: 'Thunderclap' },
  { category: 'Power Surge', title: 'First Electrocution' },
  { category: 'Unstable Bomber', title: 'Point Detonation' },
  { category: 'Unstable Bomber', title: 'Delayed Blast' },
  { category: 'Shrapnel', title: 'Explosive Shrapnel' },
  { category: 'Shrapnel', title: 'Shrapnel Carnage' },
  { category: 'Fast Gunner', title: 'Gunslinger' },
  { category: 'Fast Gunner', title: 'Blitzkrieg' },
  { category: 'Bull Eye', title: 'Targeted Strike' },
  { category: 'Bull Eye', title: 'Most Wanted' },
  { category: 'Fortress Warfare', title: 'Light Cannon' },
  { category: 'Fortress Warfare', title: 'Unbreakable' },
  { category: 'Bounce', title: 'Precision Bounce' },
  { category: 'Bounce', title: 'Break Bounce' },
];
export const glovesOptions = [
  { category: 'Key', title: 'Hardy Gloves' },
  { category: 'Key', title: 'BBQ Gloves' },
  { category: 'Key', title: 'Drifter Gauntlets' },
  { category: 'Key', title: 'Snow Camo Gloves' },
  ...setItems,
];
export const gmodOptions = [
  'Lifeforce Boost',
  'Crit Amplifier',
  'Crit Boost',
  'Elemental Overload',
  'Status Enhancement',
  'Munitions Amplifier',
  'Weakspot DMG Boost',
  'Melee Amplifier',
];
export const topOptions = [
  { category: 'Key', title: 'Frost Tactical Vest' },
  { category: 'Key', title: 'Explosive Front Top' },
  { category: 'Key', title: 'Shaman Vulture Top' },
  { category: 'Key', title: 'Shelter Walker Wrap' },
  { category: 'Key', title: "Doyen's Cloak" },
  { category: 'Key', title: 'Sleek Leather Jacket' },
  { category: 'Key', title: 'Charmed Mag Top' },
  ...setItems,
];
export const tmodOptions = [
  'Lifeforce Boost',
  'Status Enhancement',
  'Weakspot DMG Boost',
  'Crit DMG Enhancement',
  'Munitions Amplifier',
  'Resist Advantage',
  'Head Guard',
  'Healing Fortification',
  'Quick Comeback',
  'Enduring Shield',
  'Head-on Conflict',
  'Critical Rescue',
  'Status Immune',
  'Rejuvenating',
  'Ardent Shield',
];
export const bottomsOptions = [
  { category: 'Key', title: 'Tattoo Pants' },
  { category: 'Key', title: 'Sharp Edge Pants' },
  { category: 'Key', title: 'Hot Dog Shorts' },
  { category: 'Key', title: 'Overloaded Pants' },
  ...setItems,
];
export const bmodOptions = [
  'Lifeforce Boost',
  'Deadshot',
  'Melee Momentum',
  'Reload Rampage',
  'Unstoppable',
  'Bullet Siphon',
  'Status Amplification',
  'Precision Charge',
  'Three Strikes',
  'Elemental Resonance',
  'Critical Surge',
];
export const shoesOptions = [
  { category: 'Key', title: 'Hard Tactical Boots' },
  { category: 'Key', title: 'Cowboy Boots' },
  { category: 'Key', title: 'Season Hunter Boots' },
  { category: 'Key', title: 'Tactical Combat Shoes' },
  { category: 'Key', title: 'Leather Boots' },
  { category: 'Key', title: 'Earthly Boots' },
  { category: 'Key', title: 'Fire Rune Boots' },
  ...setItems,
];
export const smodOptions = [
  'Lifeforce Boost',
  'Covered Advance',
  'Slow and Steady',
  'Secluded Strike',
  'Ruthless Reaper Precision',
  'Ferocious Charge',
  'Rush Hour',
  'Against All Odds',
  'Power of Striving',
];
export const hideOptions = [
  'Cowhide',
  'Mountain Cowhide',
  'Valley Cowhide',
  'Deer Hide',
  'Highland Deer Hide',
  'Forest Deer Hide',
  'Tundra Deer Hide',
  'Wolf Skin',
  'Wasteland Wolf Skin',
  'Grassland Wolf Skin',
  'Jungle Wolf Skin',
  'Rabbit Fur',
  'Dreamy Rabbit Fur',
  'Lucky Rabbit Fur',
  'Wool',
  'Rock Wall Wool',
  'Mountain Wool',
  'Golden Wool',
  'Bear Skin',
  'Floating Ice Bear Skin',
  'Snowfield Bear Skin',
  'Cave Bear Skin',
  'Crocodile Hide',
  'Beach Crocodile Skin',
  'Coastal Bay Crocodile Skin',
  'Fox Skin',
  'Polar Fox Skin',
  'Desert Fox Skin',
  'Hide',
  'Velvet',
  'Sealskin',
  'Reindeer Hide',
  'Rawhide',
];